//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SvgFileTypePlugin.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new SingleAssemblyResourceManager("SvgFileTypePlugin.Localization.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Elements.
        /// </summary>
        internal static string AllElements {
            get {
                return ResourceManager.GetString("AllElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle.
        /// </summary>
        internal static string Angle {
            get {
                return ResourceManager.GetString("Angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update is available!.
        /// </summary>
        internal static string AnUpdateIsAvailable {
            get {
                return ResourceManager.GetString("AnUpdateIsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness Cutoff.
        /// </summary>
        internal static string BrightnessCutoff {
            get {
                return ResourceManager.GetString("BrightnessCutoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detects areas that are darker than the threshold value and creates a path enclosing them..
        /// </summary>
        internal static string BrightnessCutoffDesc {
            get {
                return ResourceManager.GetString("BrightnessCutoffDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled upon your request..
        /// </summary>
        internal static string CanceledUponYourRequest {
            get {
                return ResourceManager.GetString("CanceledUponYourRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canvas (W×H).
        /// </summary>
        internal static string Canvas {
            get {
                return ResourceManager.GetString("Canvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canvas is too big..
        /// </summary>
        internal static string CanvasIsTooBig {
            get {
                return ResourceManager.GetString("CanvasIsTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discussion.
        /// </summary>
        internal static string DiscussionLink {
            get {
                return ResourceManager.GetString("DiscussionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edge Detection Mode.
        /// </summary>
        internal static string EdgeDetectionMode {
            get {
                return ResourceManager.GetString("EdgeDetectionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enclose.
        /// </summary>
        internal static string Enclose {
            get {
                return ResourceManager.GetString("Enclose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Layer Group: {0}.
        /// </summary>
        internal static string EndLayerGroup {
            get {
                return ResourceManager.GetString("EndLayerGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export as Shape.
        /// </summary>
        internal static string ExportAsPdnShape {
            get {
                return ResourceManager.GetString("ExportAsPdnShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill Color.
        /// </summary>
        internal static string FillColor {
            get {
                return ResourceManager.GetString("FillColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flatten.
        /// </summary>
        internal static string Flatten {
            get {
                return ResourceManager.GetString("Flatten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub.
        /// </summary>
        internal static string GitHubLink {
            get {
                return ResourceManager.GetString("GitHubLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group boundaries.
        /// </summary>
        internal static string GroupBoundaries {
            get {
                return ResourceManager.GetString("GroupBoundaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imports group boundaries as empty layers..
        /// </summary>
        internal static string GroupBoundariesToolTip {
            get {
                return ResourceManager.GetString("GroupBoundariesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        internal static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highpass Filter Radius.
        /// </summary>
        internal static string HighpassFilterRadius {
            get {
                return ResourceManager.GetString("HighpassFilterRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppresses large-scale irregularities such as background variations, while preserving small-scale detail such as lines..
        /// </summary>
        internal static string HighpassFilterRadiusDesc {
            get {
                return ResourceManager.GetString("HighpassFilterRadiusDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden elements.
        /// </summary>
        internal static string ImportHiddenElements {
            get {
                return ResourceManager.GetString("ImportHiddenElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert.
        /// </summary>
        internal static string Invert {
            get {
                return ResourceManager.GetString("Invert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Aspect Ratio.
        /// </summary>
        internal static string KeepAspectRatio {
            get {
                return ResourceManager.GetString("KeepAspectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer Group: {0}.
        /// </summary>
        internal static string LayerGroup {
            get {
                return ResourceManager.GetString("LayerGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layers.
        /// </summary>
        internal static string Layers {
            get {
                return ResourceManager.GetString("Layers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowpass Filter Radius.
        /// </summary>
        internal static string LowpassFilterRadius {
            get {
                return ResourceManager.GetString("LowpassFilterRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smooths foreground details..
        /// </summary>
        internal static string LowpassFilterRadiusDesc {
            get {
                return ResourceManager.GetString("LowpassFilterRadiusDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure you&apos;ve enough memory!.
        /// </summary>
        internal static string MemoryWarningText {
            get {
                return ResourceManager.GetString("MemoryWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO PATH.
        /// </summary>
        internal static string NoPath {
            get {
                return ResourceManager.GetString("NoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element opacity as layer property.
        /// </summary>
        internal static string OpacityAsLayerProperty {
            get {
                return ResourceManager.GetString("OpacityAsLayerProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimize.
        /// </summary>
        internal static string Optimize {
            get {
                return ResourceManager.GetString("Optimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to optimize paths by joining adjacent Bezier curve segments..
        /// </summary>
        internal static string OptimizeDesc {
            get {
                return ResourceManager.GetString("OptimizeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paint.NET Shape Export Options.
        /// </summary>
        internal static string PdnShapeExportOptions {
            get {
                return ResourceManager.GetString("PdnShapeExportOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Enter a display name for the shape.
        /// </summary>
        internal static string PdnShapeExportOptionsDesc {
            get {
                return ResourceManager.GetString("PdnShapeExportOptionsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin Version: {0}.
        /// </summary>
        internal static string PluginVersion {
            get {
                return ResourceManager.GetString("PluginVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Mode.
        /// </summary>
        internal static string PreviewMode {
            get {
                return ResourceManager.GetString("PreviewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast.
        /// </summary>
        internal static string PreviewModeFast {
            get {
                return ResourceManager.GetString("PreviewModeFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow.
        /// </summary>
        internal static string PreviewModeSlow {
            get {
                return ResourceManager.GetString("PreviewModeSlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready!.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution (DPI).
        /// </summary>
        internal static string Resolution {
            get {
                return ResourceManager.GetString("Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        internal static string Scale {
            get {
                return ResourceManager.GetString("Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale before threshold.
        /// </summary>
        internal static string ScaleBeforeThreshold {
            get {
                return ResourceManager.GetString("ScaleBeforeThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Mode.
        /// </summary>
        internal static string ScanMode {
            get {
                return ResourceManager.GetString("ScanMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opaque.
        /// </summary>
        internal static string ScanModeOpaque {
            get {
                return ResourceManager.GetString("ScanModeOpaque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparent.
        /// </summary>
        internal static string ScanModeTransparent {
            get {
                return ResourceManager.GetString("ScanModeTransparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shape.
        /// </summary>
        internal static string Shape {
            get {
                return ResourceManager.GetString("Shape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image tracing result is saved as Paint.NET Shape.
        ///-----
        ///{0}
        ///-----.
        /// </summary>
        internal static string ShapeSaved {
            get {
                return ResourceManager.GetString("ShapeSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string ShapeSavedCaption {
            get {
                return ResourceManager.GetString("ShapeSavedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must restart Paint.NET to use it..
        /// </summary>
        internal static string ShapeSavedRestart {
            get {
                return ResourceManager.GetString("ShapeSavedRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size selection by user.
        /// </summary>
        internal static string SizeSelectionByUser {
            get {
                return ResourceManager.GetString("SizeSelectionByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size settings given in SVG file.
        /// </summary>
        internal static string SizeSettingsGivenInSvgFile {
            get {
                return ResourceManager.GetString("SizeSettingsGivenInSvgFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smooth Corners.
        /// </summary>
        internal static string SmoothCorners {
            get {
                return ResourceManager.GetString("SmoothCorners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smooth out sharp corners of the trace..
        /// </summary>
        internal static string SmoothCornersDesc {
            get {
                return ResourceManager.GetString("SmoothCornersDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppress Speckles.
        /// </summary>
        internal static string SuppressSpeckles {
            get {
                return ResourceManager.GetString("SuppressSpeckles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore small spots (speckles) in the bitmap..
        /// </summary>
        internal static string SuppressSpecklesDesc {
            get {
                return ResourceManager.GetString("SuppressSpecklesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tight.
        /// </summary>
        internal static string Tight {
            get {
                return ResourceManager.GetString("Tight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Policy.
        /// </summary>
        internal static string TurnPolicy {
            get {
                return ResourceManager.GetString("TurnPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        internal static string TurnPolicyBlack {
            get {
                return ResourceManager.GetString("TurnPolicyBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines how to resolve ambiguities during decomposition of bitmaps into paths..
        /// </summary>
        internal static string TurnPolicyDesc {
            get {
                return ResourceManager.GetString("TurnPolicyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string TurnPolicyLeft {
            get {
                return ResourceManager.GetString("TurnPolicyLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Majority.
        /// </summary>
        internal static string TurnPolicyMajority {
            get {
                return ResourceManager.GetString("TurnPolicyMajority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minority.
        /// </summary>
        internal static string TurnPolicyMinority {
            get {
                return ResourceManager.GetString("TurnPolicyMinority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        internal static string TurnPolicyRandom {
            get {
                return ResourceManager.GetString("TurnPolicyRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string TurnPolicyRight {
            get {
                return ResourceManager.GetString("TurnPolicyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        internal static string TurnPolicyWhite {
            get {
                return ResourceManager.GetString("TurnPolicyWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        internal static string Untitled {
            get {
                return ResourceManager.GetString("Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ▼ Use size settings given in SVG ▼.
        /// </summary>
        internal static string UseSizeSettingsGivenInSvg {
            get {
                return ResourceManager.GetString("UseSizeSettingsGivenInSvg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewBox (W×H).
        /// </summary>
        internal static string ViewBoxWH {
            get {
                return ResourceManager.GetString("ViewBoxWH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewBox (X,Y).
        /// </summary>
        internal static string ViewBoxXY {
            get {
                return ResourceManager.GetString("ViewBoxXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewport (W×H).
        /// </summary>
        internal static string Viewport {
            get {
                return ResourceManager.GetString("Viewport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working....
        /// </summary>
        internal static string Working {
            get {
                return ResourceManager.GetString("Working", resourceCulture);
            }
        }
    }
}
